fieldtypes = [
    {'name': 'ancestor_path',
     'class': 'solr.TextField',
     'indexAnalyzer': {'tokenizer': {'class': 'solr.KeywordTokenizerFactory'}},
     'queryAnalyzer': {'tokenizer': {'class': 'solr.PathHierarchyTokenizerFactory', 'delimiter': '/'}}},
    {'name': 'descendent_path',
     'class': 'solr.TextField',
     'indexAnalyzer': {'tokenizer': {'class': 'solr.PathHierarchyTokenizerFactory', 'delimiter': '/'}},
     'queryAnalyzer': {'tokenizer': {'class': 'solr.KeywordTokenizerFactory'}}},
    {'name': 'important_string',
     'class': 'solr.StrField',
     'indexed': True,
     'stored': True,
     'sortMissingLast': True,
     'docValues': True,
     'multiValued': False},
    {'name': 'important_strings',
     'class': 'solr.StrField',
     'indexed': True,
     'stored': True,
     'sortMissingLast': True,
     'docValues': True,
     'multiValued': True},
    {'name': 'pdate',
     'class': 'solr.DatePointField',
     'stored': True,
     'docValues': True},
    {'name': 'pint', 'class': 'solr.IntPointField', 'docValues': True},
    {'name': 'plong', 'class': 'solr.LongPointField', 'docValues': True},
    {'name': 'pub_type',
     'class': 'solr.EnumFieldType',
     'enumsConfig': 'enumsConfig.xml',
     'docValues': True,
     'enumName': 'ptype'},
    {'name': 'string',
     'class': 'solr.StrField',
     'sortMissingLast': True,
     'docValues': True},
    {'name': 'strings',
     'class': 'solr.StrField',
     'sortMissingLast': True,
     'docValues': True,
     'multiValued': True},
    {'name': 'text_general',
     'class': 'solr.TextField',
     'positionIncrementGap': '100',
     'multiValued': True}
]

copyFields = [
    {'source': 'key', 'dest': 'key_ancestor'},
    {'source': 'key', 'dest': 'key_descendent'}
]

fields = [
    {'name': '_root_',
     'type': 'string',
     'docValues': False,
     'indexed': True,
     'stored': False},
    {'name': '_text_',
     'type': 'text_general',
     'multiValued': True,
     'indexed': True,
     'stored': False},
    {'name': '_version_', 'type': 'plong', 'indexed': False, 'stored': False},
    {'name': 'address', 'type': 'important_string'},
    {'name': 'author', 'type': 'important_strings'},
    {'name': 'booktitle', 'type': 'important_string'},
    {'name': 'cdate', 'type': 'pdate'},
    {'name': 'cdrom', 'type': 'important_strings'},
    {'name': 'chapter', 'type': 'important_string'},
    {'name': 'cite', 'type': 'important_strings'},
    {'name': 'crossref', 'type': 'important_strings'},
    {'name': 'editor', 'type': 'important_strings'},
    {'name': 'ee', 'type': 'important_strings'},
    {'name': 'isbn', 'type': 'important_strings'},
    {'name': 'journal', 'type': 'important_string'},
    {'name': 'key',
     'type': 'string',
     'multiValued': False,
     'indexed': True,
     'required': True,
     'stored': True},
    {'name': 'key_ancestor',
     'type': 'ancestor_path',
     'multiValued': False,
     'indexed': True,
     'stored': True},
    {'name': 'key_descendent',
     'type': 'descendent_path',
     'multiValued': False,
     'indexed': True,
     'stored': True},
    {'name': 'mdate', 'type': 'pdate'},
    {'name': 'month', 'type': 'important_string'},
    {'name': 'note', 'type': 'important_strings'},
    {'name': 'number', 'type': 'important_string'},
    {'name': 'pages', 'type': 'important_strings'},
    {'name': 'pub_type', 'type': 'pub_type'},
    {'name': 'pub_type_str', 'type': 'important_string'},
    {'name': 'publisher', 'type': 'important_strings'},
    {'name': 'publnr', 'type': 'important_strings'},
    {'name': 'publtype', 'type': 'important_string'},
    {'name': 'school', 'type': 'important_strings'},
    {'name': 'series', 'type': 'important_strings'},
    {'name': 'title', 'type': 'important_string'},
    {'name': 'url', 'type': 'important_strings'},
    {'name': 'volume', 'type': 'important_strings'},
    {'name': 'year', 'type': 'pdate'}
]
